name: K6 Load Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ✅ Run k6 test and generate HTML report
      - name: Run k6 Load Test with HTML Report
        uses: grafana/k6-action@v0.3.1
        with:
          filename: tests/main.js
          flags: --summary-export=results/summary.json
        env:
          BASE_URL: https://super.2klips.com
          FEED_API: /api/posts
          TOKEN: ${{ secrets.K6_TOKEN }}
          MAX_VUS: 1000
          STEP_VUS: 100
          STEP_DURATION: 10s

      # ✅ Upload results
      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: k6-html-report
          path: results/report.html

      - name: Upload JSON Summary
        uses: actions/upload-artifact@v4
        with:
          name: k6-summary-json
          path: results/summary.json
