name: K6 Load Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run k6 Load Test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: tests/main.js
        env:
          BASE_URL: https://super.2klips.com
          FEED_API: /api/posts

          # 🔐 Secure token from GitHub Secrets
          TOKEN: ${{ secrets.K6_TOKEN }}

          # ⚙️ Load config
          MAX_VUS: 1000
          STEP_VUS: 100
          STEP_DURATION: 10s
